name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build with Gradle
        run: ./gradlew build --stacktrace